### ISSUE TITLE
Cursor jumping to end of file on save

### ISSUE THREAD

**Issue by daronspence** [kapalla/nova-laravel-pint#2]
I don't think this used to happen, but recently, whenever I save a PHP file, my cursor always jumps to the bottom of the file after formatting.

I'm not sure what changed, but it's pretty disruptive. Any ideas?

Thanks!

Edit: a little update, I did disable the plugin and tried running `pint` manually (which I believe is all this plugin does) and the same behavior occurs. Idk if it's possible to save the cursor position and then reset it?

**Comment by kapalla** [comment]
I haven't noticed this behavior yet, but I'll check on Monday.

**Comment by kapalla** [comment]
@daronspence In fact, the cursor always seems to jump to the end. I have just compared it with the previous version. However, I have never consciously noticed this behavior. I have now released v1.0.2 which resumes the original cursor position after formatting.

**Comment by daronspence** [comment]
Thanks @kapalla !
