### ISSUE TITLE
Jump to the end of the file

### ISSUE THREAD

**Issue by kirilldakhniuk** [kapalla/nova-laravel-pint#3]
Hey,

I see that in this issue https://github.com/kapalla/nova-laravel-pint/issues/2 jumping cursor problem was solved. However I noticed that while cursor keeps the original position extensions make a jump to the end of the file.

**Comment by kapalla** [comment]
@kirilldakhniuk I've just released v.1.04 which should fix it.

**Comment by kirilldakhniuk** [comment]
@kapalla  thanks for the update. It works now. But it seems like it jumps to the end of the file and jumps to the place where cursor was after ... :)

**Comment by kapalla** [comment]
That's exactly what happens. I will have a look at this when I get the chance to see if there is a better way. So far I haven't been able to find out why Nova jumps to the end and how I can prevent it. This patch does nothing more than scroll back to the cursor after formatting.

**Comment by kirilldakhniuk** [comment]
Yeah, I do hope that with Nova 12 some better way of doing thing would be available. Thanks.
